trigger:
  branches:
    include: [master, develop, "release-*" ]
  paths:
    exclude: ["*.md", .gitignore]
  tags:
    include: ["v*"]

# PR always trigger build

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

jobs:

##############################
- job: Build_Library
  condition: or( eq(variables['UPDATE_DEPENDENTS'], 'false'), eq(variables['StartReleaseCandidate'], 'true') )
  pool:
    vmImage: 'windows-2019'

  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    nugetPackageName: 'nanoFramework.Runtime.Events'
    repoName: 'lib-nanoFramework.Runtime.Events'

  steps:

  # step from template @ nf-tools repo
  # all build, update and publish steps
  - template: azure-pipelines-templates/class-lib-build.yml@templates
    parameters:
      sonarCloudProject: 'nanoframework_lib-nanoFramework.Runtime.Events'

##############################
- job: Update_Dependents
  condition: or( and( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['StartReleaseCandidate'], 'false') ), and( succeeded(), contains(variables['getCommitMessage.COMMIT_MESSAGE'], '***UPDATE_DEPENDENTS***'), eq(variables['StartReleaseCandidate'], 'false') ), eq(variables['UPDATE_DEPENDENTS'], 'true') )

  dependsOn:
  - Build_Library

  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  steps:
  # need this here in order to persist GitHub credentials 
  - checkout: self
    fetchDepth: 1

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '5.4.0'
    condition: ne( variables['StartReleaseCandidate'], true )
    displayName: 'Install specific version of NuGet'

  # update dependencies
  - task: UpdatenFDependencies@1
    inputs:
      gitHubToken: $(GitHubToken)
      repositoriesToUpdate: |
        lib-nanoFramework.Devices.Can
        lib-nanoFramework.Hardware.Esp32
        lib-nanoFramework.System.Net
        lib-nanoFramework.Graphics
        lib-Windows.Devices.Gpio
        lib-System.Device.Gpio
        lib-Windows.Devices.WiFi
        lib-Windows.Devices.SerialCommunication
        lib-Windows.Storage
    displayName: Update dependent class libs

##################################
# report build failure to Discord
- job: Report_Build_Failure
  
  dependsOn:
  - Build_Library
  - Update_Dependents
  condition: or( failed('Build_Library'), failed('Update_Dependents'))

  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  
  - checkout: self

  # step from template @ nf-tools repo
  # report error
  - template: azure-pipelines-templates/discord-webhook-task.yml@templates  
    parameters:
      status: 'failure'
      webhookUrl: '$(DiscordWebhook)'
      message: ''
